### ISSUE TITLE
Sync process

### ISSUE THREAD

**Issue by pankus** [whiskyechobravo/kerko#12]
I have a very trivial question about the synchronization process.
As I read from the documentation, on the first startup I have to run the `flask kerko sync` command. In case my Zotero collection is updated, are subsequent updates automatic, or do I have to run the `flask kerko sync` command again?
In the second case, is there any way to automate the process?

**Comment by davidlesieur** [comment]
Updates only happen when you run the `flask kerko sync` command. The usual way to automate this is to have a scheduling system to run the command regularly, e.g., cron, anacron. [This installation guide](https://gist.github.com/davidlesieur/e1dafd09636a4bb333ad360e4b2c5d6d), which includes setting up the cron job, could serve as an example.
