### ISSUE TITLE
Deployment on Github Pages

### ISSUE THREAD

**Issue by roaldarbol** [whiskyechobravo/kerko#23]
Hi - just came across this project and I think it's absolutely brilliant! 
I host my personal website on GH Pages and was thus wondering whether it is possible to deploy directly there? Maybe there could be a GH Action that could enable that? (it's not my field of expertise, I'm just grasping at straws here). 
EDIT: This could possibly rely on the Docker image.

It would make it a lot easier to deploy for us less tech-savvy people who just really want to share our thought through what we are reading (and currently I'm thinking of using a heavily filtered version for conferences, so people can find citations through a QR code that takes them to a Kerko site).

Cheers, Mikkel

**Comment by davidlesieur** [comment]
Glad that you like the project! Kerko is a dynamic, server-rendered application, and that means it cannot be hosted on GitHub Pages, which can only host static files. Unfortunately, at the moment there is no way to avoid a more involved hosting solution...

**Comment by roaldarbol** [comment]
Ah, that's unfortunate. Would have been great. Could you imagine a way that it could be served as a static page? (this is just thinking out loud, so if it's not a priority, no worries). E.g. that the content, the references, gets pulled as part of a build process, either locally or as a GH workflow/action, and then gets served.

**Comment by davidlesieur** [comment]
It would be challenging to make such an architecture work well with large databases and with full-text search. That would also require a completely different technology stack. I don't expect that Kerko will go in that direction! Something like [Zotsite](https://github.com/plandes/zotsite) might be closer to what you're looking for.

**Comment by roaldarbol** [comment]
No problem, I'll continue my search. Still, good job on this, I'm really impressed by the the UX here - hoping to find something sufficiently close. :-)

**Comment by davidlesieur** [comment]
Thanks for sharing your thoughts on this, and I wish you success with your project!
